version: 2

models:
  - name: customers
    description: 'cleaned up table of customers'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: monthly_customers
    description: 'aggregated customers per month'
    columns:
      - name: signup_month
        tests:
          - unique
          - not_null